# Generated by Django 4.2.7 on 2023-12-07 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vlan_id', models.IntegerField(validators=[django.core.validators.RegexValidator(message='Le VLAN ID doit contenir uniquement des entiers positifs.', regex='^[0-9]*$')])),
            ],
        ),
    ]
