# Generated by Django 4.2.7 on 2023-12-10 16:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('network', '0005_vlan_description_alter_vlan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlan',
            name='number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=2, message='Le VLAN ID doit être supérieur à 1.'), django.core.validators.MaxValueValidator(limit_value=4095, message='Le VLAN ID doit être inférieur à 4096.')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vlan',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vlan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
