# Generated by Django 4.2.7 on 2023-12-13 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_rename_vlan_network_vlan_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='network_CIDR',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(32)]),
        ),
    ]
