# Generated by Django 4.2.7 on 2023-12-13 10:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_network_network_cidr'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='network_address',
            field=models.CharField(default='', max_length=15, validators=[django.core.validators.validate_ipv4_address]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='network',
            name='network_broadcast',
            field=models.CharField(default='', max_length=15, validators=[django.core.validators.validate_ipv4_address]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='network',
            name='vlan_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.vlan'),
        ),
    ]
