# Generated by Django 4.2.7 on 2023-12-13 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_network_network_address_network_network_broadcast_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='network_address',
        ),
        migrations.RemoveField(
            model_name='network',
            name='network_broadcast',
        ),
    ]
