# Generated by Django 4.2.7 on 2023-12-13 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_remove_network_network_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='nb_hosts',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='network_CIDR',
            field=models.IntegerField(default=0, unique=True, validators=[django.core.validators.MaxValueValidator(32)]),
        ),
    ]
