# Generated by Django 4.2.7 on 2023-12-13 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_alter_network_nb_hosts_alter_network_network_cidr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='network_CIDR',
            new_name='CIDR',
        ),
        migrations.RenameField(
            model_name='network',
            old_name='network_mask',
            new_name='mask',
        ),
    ]
