# Generated by Django 4.2.7 on 2023-12-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_address_user_address_vlan_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='vlan_id',
            new_name='vlan',
        ),
        migrations.RenameField(
            model_name='network',
            old_name='vlan_id',
            new_name='vlan',
        ),
    ]
