# Generated by Django 4.2.7 on 2023-12-15 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('network', '0017_rename_vlan_id_address_vlan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('user', 'ip')},
        ),
        migrations.RemoveField(
            model_name='address',
            name='network',
        ),
    ]
