# Generated by Django 4.2.7 on 2023-12-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_alter_network_id_alter_address_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='hostname',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
