# Generated by Django 4.2.7 on 2024-01-09 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_address_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='ip',
            field=models.CharField(max_length=15, validators=[django.core.validators.validate_ipv4_address]),
        ),
    ]
