# Generated by Django 4.2.7 on 2023-12-07 10:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_remove_vlan_vlan_id_alter_vlan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlan',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(blank=True, max_length=32, null=True)),
                ('network_mask', models.CharField(max_length=15, validators=[django.core.validators.validate_ipv4_address])),
                ('network_address', models.CharField(max_length=15, validators=[django.core.validators.validate_ipv4_address])),
                ('network_broadcast', models.CharField(max_length=15, validators=[django.core.validators.validate_ipv4_address])),
                ('vlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.vlan')),
            ],
        ),
    ]
