# Generated by Django 4.2.7 on 2023-12-07 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlan',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vlan',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(limit_value=2, message='Le VLAN ID doit être supérieur à 1.'), django.core.validators.MaxValueValidator(limit_value=4095, message='Le VLAN ID doit être inférieur à 4096.')]),
        ),
    ]
