# Generated by Django 4.2.7 on 2023-12-15 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lechat76_site', '0002_alter_customuser_options_alter_customuser_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
    ]
