# Generated by Django 4.2.7 on 2023-12-07 10:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_vlan_name_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('ip', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.validate_ipv4_address])),
                ('description', models.CharField(blank=True, max_length=32, null=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.network')),
            ],
        ),
    ]
