# Generated by Django 4.2.7 on 2023-12-11 09:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('network', '0006_vlan_number_vlan_user_alter_vlan_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vlan',
            unique_together={('user', 'number')},
        ),
    ]
